insert into quotes (content, author, category) values
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Success'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Success'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'Motivation'),
('What you get by achieving your goals is not as important as what you become by achieving your goals.', 'Zig Ziglar', 'Success'),
('Hard work beats talent when talent doesn''t work hard.', 'Tim Notke', 'Success'),
('The best way to predict the future is to invent it.', 'Alan Kay', 'Success'),
('Opportunities don''t happen. You create them.', 'Chris Grosser', 'Success'),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas Edison', 'Success'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Success'),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller Jr.', 'Success'),
-- Motivation
('It always seems impossible until it''s done.', 'Nelson Mandela', 'Motivation'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'Motivation'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'Motivation'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'Motivation'),
('Aim for the moon. If you miss, you may hit a star.', 'W. Clement Stone', 'Motivation'),
('Your talent determines what you can do. Your motivation determines how much you are willing to do. Your attitude determines how well you do it.', 'Lou Holtz', 'Motivation'),
('Change your thoughts and you change your world.', 'Norman Vincent Peale', 'Motivation'),
('Act as if what you do makes a difference. It does.', 'William James', 'Motivation'),
('Light tomorrow with today!', 'Elizabeth Barrett Browning', 'Motivation'),
('Never, never, never give up.', 'Winston Churchill', 'Motivation'),
-- Wisdom
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Wisdom'),
('Knowledge speaks, but wisdom listens.', 'Jimi Hendrix', 'Wisdom'),
('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', 'Wisdom'),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Wisdom'),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'Wisdom'),
('In the end, it''s not the years in your life that count. It''s the life in your years.', 'Abraham Lincoln', 'Wisdom'),
('Count your age by friends, not years. Count your life by smiles, not tears.', 'John Lennon', 'Wisdom'),
('Honesty is the first chapter in the book of wisdom.', 'Thomas Jefferson', 'Wisdom'),
('The simple things are also the most extraordinary things, and only the wise can see them.', 'Paulo Coelho', 'Wisdom'),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'Wisdom'),
-- Love
('Love all, trust a few, do wrong to none.', 'William Shakespeare', 'Love'),
('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu', 'Love'),
('Where there is love there is life.', 'Mahatma Gandhi', 'Love'),
('The best thing to hold onto in life is each other.', 'Audrey Hepburn', 'Love'),
('Love is composed of a single soul inhabiting two bodies.', 'Aristotle', 'Love'),
('You know you''re in love when you can''t fall asleep because reality is finally better than your dreams.', 'Dr. Seuss', 'Love'),
('A successful marriage requires falling in love many times, always with the same person.', 'Mignon McLaughlin', 'Love'),
('Love looks not with the eyes, but with the mind.', 'William Shakespeare', 'Love'),
('The heart has its reasons which reason knows nothing of.', 'Blaise Pascal', 'Love'),
('We are shaped and fashioned by what we love.', 'Johann Wolfgang von Goethe', 'Love'),
-- Humor
('A day without laughter is a day wasted.', 'Charlie Chaplin', 'Humor'),
('I am so clever that sometimes I don''t understand a single word of what I am saying.', 'Oscar Wilde', 'Humor'),
('I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.', 'Groucho Marx', 'Humor'),
('People say nothing is impossible, but I do nothing every day.', 'A.A. Milne', 'Humor'),
('My doctor told me that jogging could add years to my life. I think he was right. I feel ten years older already.', 'Milton Berle', 'Humor'),
('I didn''t fail the test. I just found 100 ways to do it wrong.', 'Benjamin Franklin', 'Humor'),
('Always remember that you are absolutely unique. Just like everyone else.', 'Margaret Mead', 'Humor'),
('The safe way to double your money is to fold it over once and put it in your pocket.', 'Kin Hubbard', 'Humor'),
('If you think you are too small to make a difference, try sleeping with a mosquito.', 'Dalai Lama', 'Humor'),
('If at first you don''t succeed, then skydiving isn''t for you.', 'Steven Wright', 'Humor'),
-- Adding more to reach 100+
('Everything you''ve ever wanted is on the other side of fear.', 'George Addair', 'Motivation'),
('Don''t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'Roy T. Bennett', 'Motivation'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'Motivation'),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', 'Motivation'),
('Success isn''t just about what you accomplish in your life; it''s about what you inspire others to do.', 'Unknown', 'Success'),
('Failure is a great teacher, and I think when you make mistakes and recover from them and you treat them as valuable learning experiences, then you''ve got something to share.', 'Steve Harvey', 'Wisdom'),
('Life is what happens when you''re busy making other plans.', 'John Lennon', 'Wisdom'),
('Spread love everywhere you go. Let no one ever come to you without leaving happier.', 'Mother Teresa', 'Love'),
('Be kind whenever possible. It is always possible.', 'Dalai Lama', 'Wisdom'),
('Happiness is not something ready made. It comes from your own actions.', 'Dalai Lama', 'Wisdom'),
('I have decided to stick with love. Hate is too great a burden to bear.', 'Martin Luther King Jr.', 'Love'),
('Love is an untamed force. When we try to control it, it destroys us. When we try to imprison it, it enslaves us. When we try to understand it, it leaves us feeling lost and confused.', 'Paulo Coelho', 'Love'),
('Success is not how high you have climbed, but how you make a positive difference to the world.', 'Roy T. Bennett', 'Success'),
('The best revenge is massive success.', 'Frank Sinatra', 'Success'),
('Instruction ends in the schoolroom, but education ends only with life.', 'Frederick W. Robertson', 'Wisdom'),
('He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', 'Wisdom'),
('Life is short, and it is up to you to make it sweet.', 'Sarah Louise Delany', 'Wisdom'),
('I like long walks, especially when they are taken by people who annoy me.', 'Noel Coward', 'Humor'),
('Whatever you are, be a good one.', 'Abraham Lincoln', 'Motivation'),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', 'Motivation'),
('Dream big and dare to fail.', 'Norman Vaughan', 'Success'),
('It is never too late to be what you might have been.', 'George Eliot', 'Motivation'),
('The power of imagination makes us infinite.', 'John Muir', 'Wisdom'),
('The more I read, the more I acquire, the more certain I am that I know nothing.', 'Voltaire', 'Wisdom'),
('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'Ralph Waldo Emerson', 'Wisdom'),
('If you tell the truth, you don''t have to remember anything.', 'Mark Twain', 'Wisdom'),
('Life is 10% what happens to us and 90% how we react to it.', 'Charles R. Swindoll', 'Wisdom'),
('The only thing we have to fear is fear itself.', 'Franklin D. Roosevelt', 'Wisdom'),
('Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson', 'Wisdom'),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Success'),
('If you are going through hell, keep going.', 'Winston Churchill', 'Motivation'),
('Logic will get you from A to B. Imagination will take you everywhere.', 'Albert Einstein', 'Wisdom'),
('The mind is everything. What you think you become.', 'Buddha', 'Wisdom'),
('The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.', 'Helen Keller', 'Love'),
('Keep your face always toward the sunshine - and shadows will fall behind you.', 'Walt Whitman', 'Motivation'),
('The only real mistake is the one from which we learn nothing.', 'Henry Ford', 'Success'),
('Everything has beauty, but not everyone sees it.', 'Confucius', 'Wisdom'),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'Wisdom'),
('If you want to live a happy life, tie it to a goal, not to people or things.', 'Albert Einstein', 'Success'),
('The two most important days in your life are the day you are born and the day you find out why.', 'Mark Twain', 'Wisdom'),
('The heart wants what it wants. There''s no logic to these things. You meet someone and you fall in love and that''s that.', 'Woody Allen', 'Love'),
('Age is something that doesn''t matter, unless you are a cheese.', 'Luis Bunuel', 'Humor'),
('Procrastination is the art of keeping up with yesterday.', 'Don Marquis', 'Humor'),
('Common sense is like deodorant. The people who need it most never use it.', 'Anonymous', 'Humor'),
('I am an optimist. It does not seem too much use being anything else.', 'Winston Churchill', 'Wisdom'),
('When you reach the end of your rope, tie a knot in it and hang on.', 'Franklin D. Roosevelt', 'Motivation'),
('Tell me and I forget. Teach me and I remember. Involve me and I learn.', 'Benjamin Franklin', 'Wisdom'),
('The best way to cheer yourself up is to try to cheer somebody else up.', 'Mark Twain', 'Motivation'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'Wisdom'),
('The journey is the reward.', 'Steve Jobs', 'Success'),
('I have no special talent. I am only passionately curious.', 'Albert Einstein', 'Wisdom'),
('Imagination is more important than knowledge.', 'Albert Einstein', 'Wisdom'),
('The unexamined life is not worth living.', 'Socrates', 'Wisdom'),
('Stay hungry, stay foolish.', 'Steve Jobs', 'Motivation');
